# Generated by Django 5.0.1 on 2024-01-26 04:38

from django.db import migrations, models

def create_answer_choices(apps, schema_editor):
    AnswerChoice = apps.get_model('app', 'AnswerChoice')  # Replace 'app' with your actual app name
    SurveyQuestion = apps.get_model('app', 'SurveyQuestion')  # Replace 'app' with your actual app name

    # Assuming you have a specific survey question associated with these choices
    some_survey_question_instance = SurveyQuestion.objects.get(pk=some_survey_question_id)

    AnswerChoice.objects.create(choice_value=1, question_id=some_survey_question_instance.id)
    AnswerChoice.objects.create(choice_value=2, question_id=some_survey_question_instance.id)
    AnswerChoice.objects.create(choice_value=3, question_id=some_survey_question_instance.id)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerchoice',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='choice_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(create_answer_choices),  # Add this line for the data migration
    ]
