# Generated by Django 5.0.1 on 2024-01-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_answerchoice_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
