# Generated by Django 5.0.1 on 2024-01-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_surveyresponse_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='choice_value',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')]),
        ),
    ]
